name: Test
on: push

jobs:
  start:
    strategy:
      matrix:
        os: [ubuntu-latest]
        pt: ["3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download code
        uses: actions/checkout@v6.0.2
      - name: Get python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: ${{ matrix.pt }}

      - name: 'Run PEP8'
        uses: quentinguidee/pep8-action@v1
        with:
          arguments: '--max-line-length=120'
      - name: run code
        run: python test.py

      - name: Download All Artifacts
        uses: actions/download-artifact@v8
        with:
          path: .
          pattern: test.txt
      - run: ls -l
