name: Test
on: push

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v6.0.2
      - name: Get python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: 3.12
      - name: run code
        run: python test.py
